### ISSUE TITLE
showDialog flutter_screenutil: ^5.3.1   flutter run --release 

### ISSUE THREAD

**Issue by zhou-Flutter** [OpenFlutter/flutter_screenutil#360]

**Comment by Mounir-Bouaiche** [comment]
Update the library version to latest in your pubspec.yaml and try again.

**Comment by Mounir-Bouaiche** [comment]
Please update to the latest version and see if error persist.

**Comment by Mounir-Bouaiche** [comment]
@zhou-Flutter I didn't hear back from you about this issue. Any news? Does recent version or master branch fixed your problem?
Btw, you can use master branch as follows:
In pubspec.yaml, replace (temporarily):
```yaml
  flutter_screenutil:
```
with
```yaml
  flutter_screenutil:
    git:
      url: https://github.com/OpenFlutter/flutter_screenutil
      branch: master
```

**Comment by Mounir-Bouaiche** [comment]
@zhou-Flutter I didn't hear back from you about this issue. Any news? Does recent version or master branch fixed your problem?
Btw, you can use master branch as follows:
In pubspec.yaml, replace (temporarily):
```yaml
  flutter_screenutil: 
```
with
```yaml
  flutter_screenutil:
    git:
      url: https://github.com/OpenFlutter/flutter_screenutil
      branch: master
```
