### ISSUE TITLE
Using SystemUiOverlayStyle App crashes  

### ISSUE THREAD

**Issue by parmarravi** [OpenFlutter/flutter_screenutil#395]
I am using 3 Lib ScreenUtil - Getx and Country Code Picker in my project

When I try to hide entire app bar or bottom nav bar  and show it again the app keeps on getting crash. 

In Case 1.)

When I remove  CountryLocalizations.delegate the app runs perfectly fine . 

localizationsDelegates: const [
                CountryLocalizations.delegate, //   Removing this precent app getting crash 
              ],

In Case 2 )

I removed screen Util and kept only Getx  and found out the app no longer crashes.

PubSpec

```

dependencies:

  flutter:
    sdk: flutter

  get: ^4.6.1
  get_it: ^7.2.0
  flutter_screenutil: ^5.5.2
  path_provider: ^2.0.10
  country_code_picker: ^2.0.2


dev_dependencies:
  json_serializable: ^6.2.0
  build_runner: ^2.1.10
  retrofit_generator: ^4.0.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
```

```
 return GestureDetector(
      onTap: () => Get.focusScope?.unfocus(),
      child: MediaQuery(
        data: MediaQueryData.fromWindow(WidgetsBinding.instance.window),
        child: ScreenUtilInit(
          splitScreenMode: false,
          minTextAdapt: true,
          designSize: const Size(393, 851),
          builder: (_) => GetMaterialApp(
              title: "Test",
              defaultTransition: Transition.fade,
              opaqueRoute: Get.isOpaqueRouteDefault,
              popGesture: Get.isPopGestureEnable,
              transitionDuration: Get.defaultDialogTransitionDuration,
              debugShowCheckedModeBanner: false,
              locale: LocalizationService.locale,
              translations: LocalizationService(),
              supportedLocales: languageSupported,
              localizationsDelegates: const [
                CountryLocalizations.delegate,     / /  Removing this to prevent the app getting crash 
              ],
              themeMode: ThemeMode.light,
              builder: (context, widget) {
                return MediaQuery(
                  data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                  child: widget!,
                );
              },
              routingCallback: (routing) => RoutingApp.routingCallback(routing),
              initialRoute: RoutingApp.ScreenARoute,
              enableLog: true,
              getPages: RoutingApp.getRoutingPages()),
        ),
      ),
    );
```

Please find the sample project link for the reference to generate the crash 

https://github.com/parmarravi/ScreenUtil-CountryCodePickerBug
